language: objective-c

before_install:
  - java -version
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install
  
script:
  - xctool -workspace orc.xcworkspace -scheme orc -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

