language: objective-c

before_install:
  - cd test/core_tests && pod install;
#  - curl -O http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock/1.52/wiremock-1.52-standalone.jar
  - java -jar wiremock-1.52-standalone.jar --record-mappings --port 8080 --verbose --root-dir "wiremock" &

script:
  - xctool test -workspace core_tests.xcworkspace -scheme core_tests -sdk iphonesimulator

after_success:
#  - curl http://localhost:8080/__admin/shutdown

